/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
import * as i2 from '@angular/common';
import * as i3 from '@angular/http';
import * as i4 from 'ngx-cookie/src/cookie-options-provider';
import * as i5 from 'ngx-cookie/src/cookie.service';
import * as i6 from 'ngx-cookie/src/cookie.factory';
import * as i7 from './system/system.service';
import * as i8 from './main/main.service';
import * as i9 from './user/user.service';
import * as i10 from './node/node.service';
import * as i11 from './file/file.service';
import * as i12 from './comment/comment.service';
import * as i13 from './taxonomy/taxonomy-term.service';
import * as i14 from './taxonomy/taxonomy-vocabulary.service';
import * as i15 from 'ngx-cookie/index';
export const Drupal7ServicesModuleNgFactory:i0.NgModuleFactory<i1.Drupal7ServicesModule> = i0.ɵcmf(i1.Drupal7ServicesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.BrowserXhr,
          i3.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i3.ResponseOptions,i3.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(5120,i3.XSRFStrategy,i3.ɵb,([] as any[])),i0.ɵmpd(4608,
          i3.XHRBackend,i3.XHRBackend,[i3.BrowserXhr,i3.ResponseOptions,i3.XSRFStrategy]),
          i0.ɵmpd(4608,i3.RequestOptions,i3.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i3.Http,i3.ɵc,[i3.XHRBackend,i3.RequestOptions]),i0.ɵmpd(4608,i4.CookieOptionsProvider,
              i4.CookieOptionsProvider,[i4.COOKIE_OPTIONS,i0.Injector]),i0.ɵmpd(5120,
              i5.CookieService,i6.cookieServiceFactory,[i4.CookieOptionsProvider]),
          i0.ɵmpd(4608,i7.SystemService,i7.SystemService,[i3.Http,i5.CookieService]),
          i0.ɵmpd(5120,i0.APP_INITIALIZER,(p0_0:any) => {
            return [i1.init(p0_0)];
          },[i7.SystemService]),i0.ɵmpd(4608,i8.MainService,i8.MainService,[i3.Http,
              i5.CookieService]),i0.ɵmpd(4608,i9.UserService,i9.UserService,[i3.Http,
              i5.CookieService]),i0.ɵmpd(4608,i10.NodeService,i10.NodeService,[i3.Http,
              i5.CookieService]),i0.ɵmpd(4608,i11.FileService,i11.FileService,[i3.Http,
              i5.CookieService]),i0.ɵmpd(4608,i12.CommentService,i12.CommentService,
              [i3.Http,i5.CookieService]),i0.ɵmpd(4608,i13.TaxonomyTermService,i13.TaxonomyTermService,
              [i3.Http,i5.CookieService]),i0.ɵmpd(4608,i14.TaxonomyVocabularyService,
              i14.TaxonomyVocabularyService,[i3.Http,i5.CookieService]),i0.ɵmpd(512,
              i2.CommonModule,i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.HttpModule,
              i3.HttpModule,([] as any[])),i0.ɵmpd(512,i15.CookieModule,i15.CookieModule,
              ([] as any[])),i0.ɵmpd(512,i1.Drupal7ServicesModule,i1.Drupal7ServicesModule,
              ([] as any[])),i0.ɵmpd(256,i4.COOKIE_OPTIONS,{},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvb3JhbmdlL0Rlc2t0b3AvcHJvamVjdHMvbnBtL25neC1kcnVwYWw3LXNlcnZpY2VzL3NyYy9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL29yYW5nZS9EZXNrdG9wL3Byb2plY3RzL25wbS9uZ3gtZHJ1cGFsNy1zZXJ2aWNlcy9zcmMvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
